apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nexus
  namespace: lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - envFrom:
            - secretRef:
                name: prod.env
          image: gcr.io/xj-vpc-host-prod/nexus:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "1.25"
              memory: 3G
            limits:
              cpu: "2.5"
              memory: 6G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
