apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nexus
  name: nexus
  namespace: lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: nexus
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: TELEMETRY_ENABLED
              value: "true"
            - name: GCP_PROJECT_ID
              value: xj-vpc-host-prod
            - name: GCP_SECRET_ID
              value: xj-services-prod-env
            - name: INGEST_URL
              value: https://lab.xj.io/
          image: gcr.io/xj-vpc-host-prod/nexus:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: nexus
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
