apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        k8s-app: space-binaural-nexus
      name: space-binaural-nexus
      namespace: yard
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          k8s-app: space-binaural-nexus
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            k8s-app: space-binaural-nexus
        spec:
          automountServiceAccountToken: true
          containers:
            - env:
                - name: TELEMETRY_ENABLED
                  value: "true"
                - name: GCP_PROJECT_ID
                  value: xj-vpc-host-prod
                - name: GCP_SECRET_ID
                  value: xj-services-prod-env
                - name: INGEST_URL
                  value: https://lab.xj.io/
                - name: SHIP_KEY
                  value: space_binaural
                - name: SHIP_KEY_ALIAS
                  value: openspace
              image: gcr.io/xj-vpc-host-prod/nexus:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              name: space-binaural-nexus
              resources:
                requests:
                  cpu: "2.5"
                  memory: 4G
                limits:
                  cpu: "3.5"
                  memory: 8G
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        k8s-app: space-binaural-ship
      name: space-binaural-ship
      namespace: yard
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          k8s-app: space-binaural-ship
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
      template:
        metadata:
          labels:
            k8s-app: space-binaural-ship
        spec:
          automountServiceAccountToken: true
          containers:
            - env:
                - name: TELEMETRY_ENABLED
                  value: "true"
                - name: GCP_PROJECT_ID
                  value: xj-vpc-host-prod
                - name: GCP_SECRET_ID
                  value: xj-services-prod-env
                - name: INGEST_URL
                  value: https://lab.xj.io/
                - name: SHIP_KEY
                  value: space_binaural
              image: gcr.io/xj-vpc-host-prod/ship:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              name: space-binaural-ship
              resources:
                requests:
                  cpu: "1.25"
                  memory: 3G
                limits:
                  cpu: "2.5"
                  memory: 5G
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          shareProcessNamespace: false
          terminationGracePeriodSeconds: 30
