version: '2'
services:

# Apps

  xj:
    container_name: xj01er1
    extends:
      file: docker-compose.common.yml
      service: runner
#    user: "1000:1000"
#    privileged: true
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    depends_on:
      - mysql
      - redis

# Builder

#  builder:
#    container_name: build01er1
#    extends:
#      file: docker-compose.common.yml
#      service: builder

# Resources

  mysql:
    container_name: mysql01er1
    image: mysql:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    container_name: redis01er1
    image: redis:3.0.7

# Network

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
