version: '2'

services:
  web:
    environment:
      APPS: hub
    container_name: web01xj1
    ports:
      - "80:80"
    extends:
      file: docker-compose.common.yml
      service: base
    depends_on:
      - mysql
      - redis

  work:
    environment:
      APPS: worker
    container_name: work01xj1
    extends:
      file: docker-compose.common.yml
      service: base
    depends_on:
      - web
      - mysql
      - redis

  mysql:
    container_name: mysql01xj1
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
      - ./log/mysql:/var/log/mysql
      - ./.mysql/conf.d:/etc/mysql/conf.d
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    container_name: redis01xj1
    image: redis:3.0.7
    ports:
      - "6300:6379"
