version: '2'

services:

  web:
    environment:
      APPS: hub
    container_name: web01xj1
    ports:
      - "80:80"
    extends:
      file: docker-compose.common.yml
      service: base
    depends_on:
      - postgres
      - redis
    restart: always

  work:
    environment:
      APPS: worker
    container_name: work01xj1
    extends:
      file: docker-compose.common.yml
      service: base
    depends_on:
      - web
      - postgres
      - redis
    restart: always

  postgres:
    container_name: postgres01xj1
    image: postgres:11.6
    volumes:
      - /var/lib/postgresql/data
      - ./log/postgres:/var/log/postgres
      - ./ops/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    restart: always

  redis:
    container_name: redis01xj1
    image: redis:3.0.7
    ports:
      - "6300:6379"
    restart: always
