version: '2.4'

services:

  nexus:
    build:
      context: .
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./build/distributions/nexus-1.0.tar:/var/app/nexus-1.0.tar
    container_name: nexus01xj1
    restart: always
    env_file:
      - .env
