version: '2.4'

services:

  postgres:
    container_name: postgres01xj1
    image: postgres:13
    network_mode: host
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  redis:
    container_name: redis01xj1
    network_mode: host
    image: redis:3.0.7
    restart: always

