# This file is deliberately not built- only extended by services in docker-compose.yml
version: '2'
services:

  base:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ops/nginx/locations:/etc/nginx/conf.d/locations
