version: '2'

services:

  web:
    container_name: web01xj1
    image: nginx:1.17.8
    volumes:
      - ./log:/var/log
      - ./ops/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ui/web-artist-mk1/build:/usr/share/nginx/html/web-artist-mk1:ro
      - ./ui/web-artist-mk3/build:/usr/share/nginx/html/web-artist-mk3:ro
      - ./ui/web-player/build:/usr/share/nginx/html/web-player:ro
      - ./ui/hub-site:/usr/share/nginx/html/hub-site:ro
    ports:
      - "80:80"
    depends_on:
      - hub
    restart: always

  hub:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./service/hub/build/distributions/hub-1.0.tar:/var/app/hub-1.0.tar
    environment:
      APP_NAME: hub
      APP_VERSION: 1.0
    container_name: hub01xj1
    ports:
      - "8042:8042"
    depends_on:
      - postgres
      - redis
    restart: always

  work:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./service/worker/build/distributions/worker-1.0.tar:/var/app/worker-1.0.tar
    environment:
      APP_NAME: worker
      APP_VERSION: 1.0
    container_name: work01xj1
    ports:
      - "8043:8043"
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    container_name: postgres01xj1
    image: postgres:11.6
    volumes:
      - /var/lib/postgresql/data
      - ./log/postgres:/var/log/postgres
      - ./ops/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    restart: always

  redis:
    container_name: redis01xj1
    image: redis:3.0.7
    ports:
      - "6300:6379"
    restart: always
