version: '2.4'

services:

  postgres:
    container_name: postgres01xj1
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data
      - ./log/postgres:/var/log/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  redis:
    container_name: redis01xj1
    image: redis:3.0.7
    restart: always
    ports:
      - "6379:6379"

