version: '2.4'

services:

  hub:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./service/hub/build/distributions/hub-1.0.tar:/var/app/hub-1.0.tar
    environment:
      APP_NAME: hub
      APP_VERSION: 1.0
    container_name: hub01xj1
    ports:
      - "8042:8042"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - xj_network

  nexus:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./service/nexus/build/distributions/nexus-1.0.tar:/var/app/nexus-1.0.tar
    environment:
      APP_NAME: nexus
      APP_VERSION: 1.0
    container_name: nexus01xj1
    ports:
      - "8043:8043"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - xj_network

  postgres:
    container_name: postgres01xj1
    image: postgres:11.6
    volumes:
      - /var/lib/postgresql/data
      - ./log/postgres:/var/log/postgres
      - ./ops/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    restart: always
    networks:
      - xj_network

  redis:
    container_name: redis01xj1
    image: redis:3.0.7
    ports:
      - "6300:6379"
    restart: always
    networks:
      - xj_network

networks:
  xj_network:
    name: xj-network
