# This file is deliberately not built- only extended by services in docker-compose.yml
version: '2'
services:

  base:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - .:/var/app/current
      - ./log:/var/log
      - ./runtime.env:/data/runtime.env
