openapi: 3.0.3
info:
  version: 1.0.0
  title: XJ Music Accounts API
servers:
  - url: http://hub.lab.svc.cluster.local:3001/api/v2
    description: XJ Music API (Service Cluster Local)
tags:
  - name: accounts
paths:
  #
  #
  "/accounts/{accountId}":
    get:
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: "332db756-4288-499d-bdf4-b919b4ea30e1"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
#
#
# Components
#
components:
  schemas:

    #
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    #
    AccountUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
