openapi: 3.0.3
info:
  version: 1.0.0
  title: XJ Music Chains API
servers:
  - url: http://hub.lab.svc.cluster.local:3001/api/v2
    description: XJ Music API (Service Cluster Local)
tags:
  - name: chains
paths:
  #
  #
  "/chains/{chainId}":
    get:
      parameters:
        - name: chainId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: "332db756-4288-499d-bdf4-b919b4ea30e1"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chain"
#
#
# Components
#
components:
  schemas:

    #
    Chain:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        templateId:
          type: string
          format: uuid
        type:
          $ref: "./templates.yaml#/components/schemas/TemplateType"
        state:
          $ref: "#/components/schemas/ChainState"
        embedKey:
          type: string
          nullable: true
        name:
          type: string
        startAt:
          type: string
        stopAt:
          type: string
        fabricatedAheadSeconds:
          type: number
          format: double
        createdAt:
          type: string
        updatedAt:
          type: string

    #
    ChainState:
      type: string
      enum:
        [
            Draft,
            Ready,
            Fabricate,
            Complete,
            Failed,
        ]