openapi: 3.0.3
info:
  version: 1.0.0
  title: XJ Music API
servers:
  - url: http://hub.lab.svc.cluster.local:3001/api/v2
    description: XJ Music API (Service Cluster Local)
paths:
  "/ready":
    get:
      summary: Readiness Check
      operationId: readinessCheck
      responses:
        "200":
          description: Ready
          content:
            application/json:
              schema:
                type: string

#
#
#
#
components:
  schemas:
    Error:
      type: object
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.