openapi: 3.0.3
info:
  version: 1.0.0
  title: XJ Music Instruments API
servers:
  - url: http://hub.lab.svc.cluster.local:3001/api/v2
    description: XJ Music API (Service Cluster Local)
tags:
  - name: instruments
paths:
  #
  #
  "/instruments/{instrumentId}":
    get:
      parameters:
        - name: instrumentId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: "332db756-4288-499d-bdf4-b919b4ea30e1"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Instrument"
#
#
# Components
#
components:
  schemas:

    #
    Instrument:
      type: object
      properties:
        id:
          type: string
          format: uuid
        libraryId:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/InstrumentType"
        state:
          $ref: "#/components/schemas/InstrumentState"
        name:
          type: string
        density:
          type: number
          format: double
        config:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    #
    InstrumentType:
      type: string
      enum:
        [
            Drum,
            PercussionLoop,
            Bass,
            Pad,
            Sticky,
            Stripe,
            Stab,
        ]

    #
    InstrumentState:
      type: string
      enum:
        [
            Draft,
            Published,
        ]

    #
    InstrumentAuthor:
      type: object
      properties:
        id:
          type: string
          format: uuid
        instrumentId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        contribution:
          type: number
          format: double
        createdAt:
          type: string
        updatedAt:
          type: string

    #
    InstrumentMeme:
      type: object
      properties:
        id:
          type: string
          format: uuid
        instrumentId:
          type: string
          format: uuid
        name:
          type: string

    InstrumentAudio:
      type: object
      properties:
        id:
          type: string
          format: uuid
        instrumentId:
          type: string
          format: uuid
        waveformKey:
          type: string
        name:
          type: string
        start:
          type: number
          format: double
        length:
          type: number
          format: double
        tempo:
          type: number
          format: double
        density:
          type: number
          format: double
        event:
          type: string
        note:
          type: string
        volume:
          type: number
          format: double
