openapi: 3.0.3
info:
  version: 1.0.0
  title: XJ Music Templates API
servers:
  - url: http://hub.lab.svc.cluster.local:3001/api/v2
    description: XJ Music API (Service Cluster Local)
tags:
  - name: templates
paths:
  #
  #
  "/templates/{templateId}":
    get:
      parameters:
        - name: templateId
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: "332db756-4288-499d-bdf4-b919b4ea30e1"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
#
#
# Components
#
components:
  schemas:

    #
    Template:
      type: object
      properties:
        id:
          type: string
          format: uuid
        accountId:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/TemplateType"
        name:
          type: string
        config:
          type: string
        embedKey:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    #
    TemplateType:
      type: string
      enum:
        [
            Preview,
            Production,
        ]

    #
    TemplateBinding:
      type: object
      properties:
        id:
          type: string
          format: uuid
        templateId:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/ContentBindingType"
        targetId:
          type: string
          format: uuid

    #
    ContentBindingType:
      type: string
      enum:
        [
            Library,
            Program,
            Instrument,
        ]

    #
    TemplatePlayback:
      type: object
      properties:
        id:
          type: string
          format: uuid
        templateId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time