name: Build and Publish Base Container Image

on:
  push:
    branches: ['main']
    tags:
      - '**'
    paths:
      - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and Publish Base Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install system packages
        run: |
          sudo apt-get -y install amazon-ecr-credential-helper

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compute Release Version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Compute Release Target
        run: |
          echo "RELEASE_TARGET=${{ secrets.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Docker Image Build
        id: dockerImageBuild
        run: |
          docker image build -t ${{env.RELEASE_TARGET}} .

      - name: Docker Push Organization
        id: dockerPushOrganization
        run: |
          docker push ${{env.RELEASE_TARGET}}
