name: "Development CI"

on:
  push:
    branches:
      - dev

jobs:
  Gradle:
    env:
      CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      CI_BOT_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    name: Gradle
    runs-on: ubuntu-18.04

    #
    services:
      #
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      #
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install system packages
        run: |
          sudo apt-get -y install ffmpeg
          sudo apt-get -y install postgresql-client
          sudo apt-get -y install amazon-ecr-credential-helper

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Authenticate with AWS Elastic Kubernetes Service (EKS)
        run: aws eks --region ${{ secrets.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          java-package: jdk

      - name: Create Postgres databases
        run: |
          createdb -h localhost -p 5432 -U postgres xj_test
        env:
          PGPASSWORD: postgres

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Run Tests
        id: test
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: Build & Push Docker Image
        id: jib
        run: "./gradlew -Penvironment=development --info --no-daemon jib"
        continue-on-error: false

      - name: Kubernetes rollout Dev/Hub
        run: "kubectl -n dev rollout restart deployment/hub"

      - name: Kubernetes rollout Dev/HubLocal
        run: "kubectl -n dev rollout restart deployment/hub-local"

      - name: Kubernetes rollout Dev/Nexus
        run: "kubectl -n dev rollout restart deployment/nexus"
