name: Kubernetes Apply (GCP)

on:
  push:
    branches:
      - prod

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Kubernetes Apply (GCP)
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: setup-gcloud-sdk
        name: Authenticate and setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_REGION }}

      - id: apply-kuberenetes-manifests
        name: Apply Kubernetes Manifests
        working-directory: .gcp-k8s
        run: |-
          kubectl apply -f .
