name: "Integration"

on:
  push:
    branches:
      - main

jobs:
  Gradle:
    env:
      GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    name: Gradle
    runs-on: ubuntu-latest

    steps:

      - name: Install system packages
        run: |
          sudo apt-get -y install amazon-ecr-credential-helper

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Authenticate with AWS Elastic Kubernetes Service (EKS)
        run: aws eks --region ${{ secrets.AWS_DEFAULT_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}

      - name: Setup JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk

      - name: Checkout
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Run Tests
        id: test
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh

      - name: Build & Push Docker Image
        id: jib
        run: "./gradlew --info --no-daemon jib"
        continue-on-error: false

      - name: Kubernetes rollout deployment/nexus
        run: |
          kubectl -n lab rollout restart deployment/nexus
          kubectl -n yard rollout restart deployment/coolair
