name: "Pull Request"

on:
  [ pull_request ]

jobs:
  Gradle:
    env:
      CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      CI_BOT_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    name: Gradle
    runs-on: ubuntu-latest

    #
    services:
      #
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      #
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get -y install ffmpeg
          sudo apt-get -y install gpac
          sudo apt-get -y install postgresql-client

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          java-package: jdk

      - name: Create Postgres databases
        run: |
          createdb -h localhost -p 5432 -U postgres xj_test
        env:
          PGPASSWORD: postgres

      - name: Checkout
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.CI_BOT_TOKEN }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Run Tests
        id: test
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: Nothing left TODO
        run: .github/nothing_left_todo.sh
