name: "Development CI"

on:
  push:
    branches:
      - dev

jobs:
  CI:
    env:
      CI_BOT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      CI_BOT_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    name: Development CI
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'

    #
    services:
      #
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 30s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get -y install ffmpeg
          sudo apt-get -y install gpac
          sudo apt-get -y install postgresql-client
          sudo apt-get -y install amazon-ecr-credential-helper

      - name: Ensure Postgres started OK
        run: sudo docker start $(docker ps -a -q)

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
          java-package: jdk

      - name: Create Postgres databases
        # while ! nc -vzw 5 localhost 5432; do sleep 1; done
        run: |
          createdb -h localhost -p 5432 -U postgres xj_test
        env:
          PGPASSWORD: postgres

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Run Tests
        run: "./gradlew --info --no-daemon build test"
        continue-on-error: false

      - name: (GCP) Authenticate and setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_REGION }}

      - name: (GCP) Build & push Docker images
        run: |
          ./gradlew --info --no-daemon \
            -PjibFromImage=gcr.io/xj-vpc-host-prod/base:latest \
            -PjibToImageRegistry=gcr.io/xj-vpc-host-prod/dev \
            jib
        continue-on-error: false

      - name: (GCP) Google Cloud Run service deployment
        run: |
          echo "FUTURE: Trigger Google Cloud Run re-deployment"


