name: "Terraform Apply"

on:
  push:
    branches:
      - dev
      - main

jobs:
  TerraformApply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false
        working-directory: tf

      - name: Terraform has been formatted correctly with `terraform fmt`
        id: fmt
        run: terraform fmt -check -chdir=tf
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color -chdir=tf
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -no-color -chdir=tf
        continue-on-error: false
