name: "Terraform Plan from PR"

on:
  pull_request

jobs:
  TerraformPlanFromPR:
    name: "Terraform Plan from PR"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false
        working-directory: .ops

      - name: Terraform has been formatted correctly with `terraform fmt`
        id: fmt
        run: terraform -chdir=.ops fmt -check
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=.ops validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=.ops plan -no-color
        continue-on-error: false

